### ISSUE TITLE
Unsupported operation when using the library with flutter web

### ISSUE THREAD

**Issue by sebastianbuechler** [appsup-dart/openid_client#36]
I am using this library with flutter web and get the following error:

```
Error: Unsupported operation: InternetAddress.ANY_IP_V4
    at Object.throw_ [as throw] (http://localhost:51179/dart_sdk.js:5032:11)
    at Function.get ANY_IP_V4 [as ANY_IP_V4] (http://localhost:51179/dart_sdk.js:55307:17)
    at Function.get anyIPv4 [as anyIPv4] (http://localhost:51179/dart_sdk.js:55304:33)
    at Function._startServer (http://localhost:51179/packages/openid_client/openid_client_io.dart.lib.js:108:81)
    at openid_client_io.Authenticator.new.authorize (http://localhost:51179/packages/openid_client/openid_client_io.dart.lib.js:85:46)
    at authorize.next (<anonymous>)
    at runBody (http://localhost:51179/dart_sdk.js:37229:34)
    at Object._async [as async] (http://localhost:51179/dart_sdk.js:37260:7)
    at openid_client_io.Authenticator.new.authorize (http://localhost:51179/packages/openid_client/openid_client_io.dart.lib.js:81:20)
    at login_view._LoginViewState.new.loginAction (http://localhost:51179/packages/dashboard/views/login/login_view.dart.lib.js:1633:38)

```

My setup is:
```
flutter doctor -v
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.870], locale de-CH)
    • Flutter version 2.0.3 at C:\src\flutter
    • Framework revision 4d7946a68d (11 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2
    • Pub download mirror https://pub.dev

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
    • Android SDK at C:\Users\SebastianBuechler\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0-rc2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\SebastianBuechler\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (3 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 10 (API 29) (emulator)
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)                            • edge          • web-javascript • Microsoft Edge 89.0.774.57

• No issues found!
```

And I am using the example for flutter on the library page.

Any idea why this does not work with flutter web?

**Comment by rbellens** [comment]
It seems you are importing `openid_client_io.dart`. This will not work in a web context. You should import `openid_client_browser.dart` instead.

**Comment by sebastianbuechler** [comment]
@rbellens I think the general question would be:

How can we expand the browser example in order to set your own details for the flow. In my case I would want to use `authorizationCodeWithPKCE` and set my `redirectUri`.

**Comment by rbellens** [comment]
There are now some more examples in the examples directory. 

The `Authenticator` classes in `openid_client_browser.dart` and `openid_client_io.dart` are mainly intended as example implementations. It would be quite easy to create custom versions tailored to your setup.
